In [1]:
import pandas as pd
import numpy as np
import os
import glob

os. getcwd()

'C:\\Users\\rivera30\\OneDrive - NYU Langone Health\\EvictionMoratoria_OD\\code'

In [2]:
fp = r"C:/Users/rivera30/OneDrive - NYU Langone Health/EvictionMoratoria_OD/data"

    
year = str(2017)
filename = "/1_raw/census_acs/acs_"+str(year)+".csv"
data = pd.read_csv(fp+filename)

In [3]:
print(list(data.columns))

['Geo_FIPS', 'Geo_GEOID', 'Geo_NAME', 'Geo_QName', 'Geo_STUSAB', 'Geo_SUMLEV', 'Geo_GEOCOMP', 'Geo_FILEID', 'Geo_LOGRECNO', 'Geo_US', 'Geo_REGION', 'Geo_DIVISION', 'Geo_STATECE', 'Geo_STATE', 'Geo_COUNTY', 'Geo_COUSUB', 'Geo_PLACE', 'Geo_PLACESE', 'Geo_TRACT', 'Geo_BLKGRP', 'Geo_CONCIT', 'Geo_AIANHH', 'Geo_AIANHHFP', 'Geo_AIHHTLI', 'Geo_AITSCE', 'Geo_AITS', 'Geo_ANRC', 'Geo_CBSA', 'Geo_CSA', 'Geo_METDIV', 'Geo_MACC', 'Geo_MEMI', 'Geo_NECTA', 'Geo_CNECTA', 'Geo_NECTADIV', 'Geo_UA', 'Geo_UACP', 'Geo_CDCURR', 'Geo_SLDU', 'Geo_SLDL', 'Geo_VTD', 'Geo_ZCTA3', 'Geo_ZCTA5', 'Geo_SUBMCD', 'Geo_SDELM', 'Geo_SDSEC', 'Geo_SDUNI', 'Geo_UR', 'Geo_PCI', 'Geo_TAZ', 'Geo_UGA', 'Geo_BTTR', 'Geo_BTBG', 'Geo_PUMA5', 'Geo_PUMA1', 'SE_A00001_001', 'SE_A14006_001', 'SE_A14028_001', 'SE_A10032_001', 'SE_A10032_002', 'SE_A10032_003', 'SE_A10032_004', 'SE_A10032_005', 'SE_A10032_006', 'SE_A10032_007', 'SE_A10032_008', 'SE_A10032_009', 'SE_A10032_010', 'SE_A10032_011', 'SE_A10032_012', 'SE_A10062B_001', 'SE_A10062B_002', 'SE_A10062B_003', 'SE_A10062B_004', 'SE_A10062B_005', 'SE_A10062B_006', 'SE_A18002_001', 'SE_A18002_002', 'SE_A18002_003', 'SE_A18002_004', 'SE_A18002_005', 'SE_A18002_006', 'SE_B18002_001', 'SE_B18002_002', 'SE_B18002_003', 'SE_A10039B_001', 'SE_A10039B_002', 'SE_A10039B_003', 'SE_A10039B_004', 'SE_A10039B_005', 'SE_A10039B_006', 'SE_A10039B_007', 'SE_A10039B_008', 'SE_A10039B_009', 'SE_A10039B_010', 'SE_A10039B_011', 'SE_A10039B_012', 'SE_A10039B_013', 'SE_A10039B_014', 'SE_A10039B_015', 'SE_A10039B_016', 'SE_A10039B_017', 'SE_A10039B_018', 'SE_A10039B_019', 'SE_A10039B_020', 'SE_A10039B_021', 'SE_A10039B_022', 'SE_A10039B_023', 'SE_A13003B_001', 'SE_A13003B_002', 'SE_A13003B_003']

In [4]:
data2 = data[["Geo_FIPS", "Geo_NAME", "SE_A00001_001", "SE_A14006_001", "SE_A10032_001", "SE_A18002_001", "SE_A10062B_001", 
              "SE_B18002_002", "SE_B18002_003", "SE_A13003B_001", "SE_A13003B_002", "SE_A14028_001"]]

In [5]:
data2.rename(columns = {"Geo_FIPS": "geofips",
                        "SE_A00001_001": "totpop", #total population
                        "SE_A14006_001": "mhhinc", #median household income
                        "SE_A10032_001":"housingunits", #number of housing units
                        "SE_A18002_001": "renterhousingunits", #numbre of renter housing units"
                        "SE_A10062B_001": "poprenterhousing", #population in household renter units
                        "SE_B18002_002": "rent30_49inc", 
                        "SE_B18002_003": "rent50plusinc", 
                        "SE_A13003B_001": "poppovertystatus", 
                        "SE_A13003B_002": "pop18_64poverty",
                        "SE_A14028_001": "gini"}, inplace = True)

data2["Year"] = year

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\rivera30\AppData\Local\Temp/ipykernel_54328/4275299177.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Year"] = year

In [6]:
data2.head()

,geofips,Geo_NAME,totpop,mhhinc,housingunits,renterhousingunits,poprenterhousing,rent30_49inc,rent50plusinc,poppovertystatus,pop18_64poverty,gini,Year
0,1001,"Autauga County, Alabama",55036,55317,23152,5624,14567,1280,1478,33451,4297,0.4501,2017
1,1003,"Baldwin County, Alabama",203360,52562,110023,20663,51150,4459,4335,117805,13777,0.4618,2017
2,1005,"Barbour County, Alabama",26201,33368,11918,3446,9102,633,727,13453,3153,0.4622,2017
3,1007,"Bibb County, Alabama",22580,43404,9112,1704,5217,363,342,12617,1591,0.4518,2017
4,1009,"Blount County, Alabama",57667,47412,24161,4444,11358,746,593,33919,4553,0.4302,2017

In [7]:
for year in range(2017, 2022):
    filename = "/1_raw/census_acs/acs_"+str(year)+".csv"
    data = pd.read_csv(fp+filename)
    
    data2 = data[["Geo_FIPS", "Geo_NAME", "SE_A00001_001", "SE_A14006_001", "SE_A10032_001", "SE_A18002_001", "SE_A10062B_001", 
              "SE_B18002_002", "SE_B18002_003", "SE_A13003B_001", "SE_A13003B_002", "SE_A14028_001"]]
    
    data2.rename(columns = {"Geo_FIPS": "geofips",
                        "SE_A00001_001": "totpop",
                        "SE_A14006_001": "mhhinc", 
                        "SE_A10032_001":"housingunits",
                        "SE_A18002_001": "renterhousingunits",
                        "SE_A10062B_001": "poprenterhousing", 
                        "SE_B18002_002": "rent30_49inc", 
                        "SE_B18002_003": "rent50plusinc", 
                        "SE_A13003B_001": "poppovertystatus", 
                        "SE_A13003B_002": "pop18_64poverty",
                        "SE_A14028_001": "gini"}, inplace = True)
    
    data2["Year"] = year
    

    # Write to a csv file
    data2.to_csv(fp+"/2_intermediate/census_acs/"+"ACSclean_"+str(year)+".csv")

    print("Done!")

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\rivera30\AppData\Local\Temp/ipykernel_54328/4232940099.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Year"] = year

Done!
Done!
Done!
Done!
Done!

In [8]:
all_files = glob.glob(os.path.join(fp+"/2_intermediate/census_acs/", "*.csv"))     # advisable to use os.path.join as this makes concatenation OS independent
df_from_each_file = (pd.read_csv(f) for f in all_files)
concatenated_acs   = pd.concat(df_from_each_file, ignore_index=True)
concatenated_acs.head()

,Unnamed: 0,geofips,Geo_NAME,totpop,mhhinc,housingunits,renterhousingunits,poprenterhousing,rent30_49inc,rent50plusinc,poppovertystatus,pop18_64poverty,gini,Year
0,0,1001,"Autauga County, Alabama",55036,55317.0,23152,5624.0,14567,1280.0,1478.0,33451.0,4297.0,0.4501,2017
1,1,1003,"Baldwin County, Alabama",203360,52562.0,110023,20663.0,51150,4459.0,4335.0,117805.0,13777.0,0.4618,2017
2,2,1005,"Barbour County, Alabama",26201,33368.0,11918,3446.0,9102,633.0,727.0,13453.0,3153.0,0.4622,2017
3,3,1007,"Bibb County, Alabama",22580,43404.0,9112,1704.0,5217,363.0,342.0,12617.0,1591.0,0.4518,2017
4,4,1009,"Blount County, Alabama",57667,47412.0,24161,4444.0,11358,746.0,593.0,33919.0,4553.0,0.4302,2017

In [9]:
list(concatenated_acs.columns)

['Unnamed: 0',
 'geofips',
 'Geo_NAME',
 'totpop',
 'mhhinc',
 'housingunits',
 'renterhousingunits',
 'poprenterhousing',
 'rent30_49inc',
 'rent50plusinc',
 'poppovertystatus',
 'pop18_64poverty',
 'gini',
 'Year']

In [10]:
concatenated_acs.to_csv(fp+"/2_intermediate/"+"acs_2017_2021"+".csv")

Create new file with more variables

In [2]:
fp = r"C:/Users/rivera30/OneDrive - NYU Langone Health/EvictionMoratoria_OD/data"

In [3]:
for year in range(2019, 2022):
    filename = "/1_raw/census_acs/acs_morevars_"+str(year)+".csv"
    data = pd.read_csv(fp+filename)
    data2 = data[["Geo_FIPS", "Geo_NAME", "Geo_STATE", "SE_B01001_001", "SE_B01001_002", "SE_B01001_003", "SE_B01001_004", "SE_B01001_005", "SE_B04001_002", 
              "SE_B04001_003", "SE_B04001_004", "SE_B04001_005", "SE_B04001_006", "SE_B04001_007", "SE_B04001_008", "SE_B04001_009", "SE_B04001_010", 
              "SE_A10002B_001", "SE_A10002B_002", "SE_A10002B_003", "SE_A10002B_004", "SE_A10002B_005", "SE_A10002B_006", "SE_A10002B_007", "SE_A10002B_008",
              "SE_B12001_001", "SE_B12001_002", "SE_B12001_003", "SE_B12001_004", "SE_A17005_001", "SE_A17005_003", "SE_A14006_001", "SE_A10017_001", 
              "SE_A10017_002", "SE_A10017_003", "SE_A10018_001", "SE_A02001_002", "SE_A02001_003",
              "SE_A10018_002", "SE_A10018_003", "SE_A10014_001", "SE_A10014_002", "SE_A10014_003", "SE_A14026_001", "SE_A14026_002", "SE_A14026_003", 
              "SE_A14026_004", "SE_A14026_005", "SE_A14028_001", "SE_A10047_001", "SE_A10047_002", "SE_A10047_003", "SE_A10047_004", "SE_A10062B_001", 
              "SE_A10062B_002", "SE_A10062B_003", "SE_A10062B_004", "SE_A10062B_005", "SE_A10062B_006", "SE_A10046B_001", "SE_A10046B_002", "SE_A10046B_003", 
              "SE_A10046B_004", "SE_A10046B_005", "SE_A10046B_006", "SE_B18002_001", "SE_B18002_002", "SE_B18002_003", "SE_A13003B_001", 
              "SE_A13003B_002", "SE_A13003B_003", "SE_D13004_001", "SE_D13004_002", "SE_D13004_003", "SE_D13004_004", "SE_D13004_005", "SE_D13004_006", 
              "SE_A20001_001", "SE_A20001_002", "SE_A20001_003", "SE_A20001_004", "SE_A20001_005", "SE_A00002_003", "SE_A00002_003"]]
    data2.rename(columns = {"Geo_STATE": "StateFIPS",
                            "Geo_FIPS": "geofips",
                        "SE_B01001_001": "totpop", #total population
                        "SE_B01001_002": "pop18under", 
                        "SE_B01001_003": "pop18_34",
                        "SE_B01001_004": "pop35to64", 
                        "SE_B01001_005": "pop65plus",
                        "SE_A02001_002": "popmale", 
                        "SE_A02001_003": "popfemale", 
                        #"SE_B04001_001",
                        "SE_B04001_002": "popNH", 
                        "SE_B04001_003": "popNHWhite", 
                        "SE_B04001_004": "popNHBlack", 
                        "SE_B04001_005": "popNHAIAN", 
                        "SE_B04001_006": "popNHAsian", 
                        "SE_B04001_007": "popNHAPI", 
                        "SE_B04001_008": "popNHOther", 
                        "SE_B04001_009": "popNH2plus", 
                        "SE_B04001_010": "popHispanic", 
                        "SE_A10002B_001": "renterocchousingunits", 
                        "SE_A10002B_002": "onepers_renterhu", 
                        "SE_A10002B_003": "twopers_renterhu", 
                        "SE_A10002B_004": "threepers_renterhu", 
                        "SE_A10002B_005": "fourpers_renterhu", 
                        "SE_A10002B_006": "fivepers_renterhu", 
                        "SE_A10002B_007": "sixpers_renterhu", 
                        "SE_A10002B_008": "sevenpluspers_renterhu",
                        "SE_B12001_001": "pop25plus", 
                        "SE_B12001_002": "lessHS", 
                        "SE_B12001_003": "highschool", 
                        "SE_B12001_004": "highschoolplus", 
                        "SE_A17005_001": "pop16plus",
                        "SE_A17005_003": "popunemp",
                        "SE_A14006_001": "mhhinc", 
                        "SE_A10017_001": "households", 
                        "SE_A10017_002": "householdsSSI", 
                        "SE_A10014_002": "housholdsPAI", 
                        "SE_A14026_001": "hhlowquintile", 
                        "SE_A14026_002": "hhsecondquintile", 
                        "SE_A14026_003": "hhthirdquintile" ,
                        "SE_A14026_004": "hhfourthquintile", 
                        "SE_A14026_005": "hhfifthquintile", 
                        "SE_A14028_001": "gini", 
                        "SE_A10047_001": "vacanthu", 
                        "SE_A10047_002": "vacanthurent", 
                        "SE_A10047_003": "vacanthusale", 
                        "SE_A10047_004": "vacanthuother", 
                        "SE_A10062B_001": "poprenterhousing",
               #         "SE_A10062B_002", 
                #        "SE_A10062B_003", 
                 #       "SE_A10062B_004", 
                  #      "SE_A10062B_005", 
                   #     "SE_A10062B_006", 
                        "SE_A10046B_001": "renterhu", 
                        "SE_A10046B_002": "occroomhalfless", 
                        "SE_A10046B_003": "occroomhalfto1", 
                        "SE_A10046B_004": "occroom1to1half", 
                        "SE_A10046B_005": "occroom1halftotwo", 
                        "SE_A10046B_006": "occroom2plus", 
                        #"SE_B18002_001", 
                        "SE_B18002_002": "rent30to49", 
                        "SE_B18002_003": "rent50plus", 
                        "SE_A13003B_001": "poppoovertystatus", 
                        "SE_A13003B_002": "popinpoverty", 
                        "SE_A13003B_003":  "popatorabovepoverty", 
                        "SE_D13004_001": "families", 
                        "SE_D13004_002": "ratioincpovunder2", 
                        "SE_D13004_003": "ratioincpov2to3", 
                        "SE_D13004_004": "ratioincpov3to4", 
                        "SE_D13004_005": "ratioincpov4to5",
                        "SE_D13004_006": "ratioincpov5plus", 
                        "SE_A20001_001": "popcivnoninspop", 
                        "SE_A20001_002": "popwithouthealthins", 
                        "SE_A20001_003": "pophealthins", 
                        "SE_A20001_004": "publichealthins", 
                        "SE_A20001_005":"privatehealthins",
                        "SE_A00002_003": "area"}, inplace = True)
    data2["Year"] = year
    
# Write to a csv file
    data2.to_csv(fp+"/2_intermediate/census_acs/new/"+"ACSclean_"+str(year)+".csv")

    print("Done!")

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\rivera30\AppData\Local\Temp\ipykernel_43672\3067358431.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Year"] = year

Done!
Done!
Done!

In [4]:
all_files = glob.glob(os.path.join(fp+"/2_intermediate/census_acs/new/", "*.csv"))     # advisable to use os.path.join as this makes concatenation OS independent
df_from_each_file = (pd.read_csv(f) for f in all_files)
concatenated_acs   = pd.concat(df_from_each_file, ignore_index=True)
concatenated_acs.head()

,Unnamed: 0,geofips,Geo_NAME,StateFIPS,totpop,pop18under,pop18_34,pop35to64,pop65plus,popNH,...,ratioincpov4to5,ratioincpov5plus,popcivnoninspop,popwithouthealthins,pophealthins,publichealthins,privatehealthins,area,area.1,Year
0,0,1001,Autauga County,1,55380,13205,11864,22028,8283,53815,...,2356,3994,54552,3856,50696,19242,38855,594.443749,594.443749,2019
1,1,1003,Baldwin County,1,212830,46235,39425,84639,42531,203119,...,6190,18946,210305,18679,191626,76905,148438,1589.822717,1589.822717,2019
2,2,1005,Barbour County,1,25361,5307,5732,9612,4710,24256,...,469,1072,22475,2544,19931,11575,11916,885.008060,885.008060,2019
3,3,1007,Bibb County,1,22493,4631,4970,9308,3584,21914,...,527,887,20632,2201,18431,8384,12491,622.461349,622.461349,2019
4,4,1009,Blount County,1,57681,13389,11340,22626,10326,52339,...,1600,3358,57217,6159,51058,19499,38888,644.830713,644.830713,2019

In [5]:
concatenated_acs.to_csv(fp+"/2_intermediate/"+"acs_2019_2021"+".csv")