In [1]:
import pandas as pd
import numpy as np
import os
import glob

os. getcwd()

'C:\\Users\\rivera30\\OneDrive - NYU Langone Health\\EvictionMoratoria_OD\\code'

In [3]:
fp = r"C:/Users/rivera30/OneDrive - NYU Langone Health/EvictionMoratoria_OD/data"

    
year = str(2017)
filename = "/1_raw/census_acs/acs_"+str(year)+".csv"
data = pd.read_csv(fp+filename)

In [4]:
print(list(data.columns))

['Geo_FIPS', 'Geo_GEOID', 'Geo_NAME', 'Geo_QName', 'Geo_STUSAB', 'Geo_SUMLEV', 'Geo_GEOCOMP', 'Geo_FILEID', 'Geo_LOGRECNO', 'Geo_US', 'Geo_REGION', 'Geo_DIVISION', 'Geo_STATECE', 'Geo_STATE', 'Geo_COUNTY', 'Geo_COUSUB', 'Geo_PLACE', 'Geo_PLACESE', 'Geo_TRACT', 'Geo_BLKGRP', 'Geo_CONCIT', 'Geo_AIANHH', 'Geo_AIANHHFP', 'Geo_AIHHTLI', 'Geo_AITSCE', 'Geo_AITS', 'Geo_ANRC', 'Geo_CBSA', 'Geo_CSA', 'Geo_METDIV', 'Geo_MACC', 'Geo_MEMI', 'Geo_NECTA', 'Geo_CNECTA', 'Geo_NECTADIV', 'Geo_UA', 'Geo_UACP', 'Geo_CDCURR', 'Geo_SLDU', 'Geo_SLDL', 'Geo_VTD', 'Geo_ZCTA3', 'Geo_ZCTA5', 'Geo_SUBMCD', 'Geo_SDELM', 'Geo_SDSEC', 'Geo_SDUNI', 'Geo_UR', 'Geo_PCI', 'Geo_TAZ', 'Geo_UGA', 'Geo_BTTR', 'Geo_BTBG', 'Geo_PUMA5', 'Geo_PUMA1', 'SE_A00001_001', 'SE_A14006_001', 'SE_A14028_001', 'SE_A10032_001', 'SE_A10032_002', 'SE_A10032_003', 'SE_A10032_004', 'SE_A10032_005', 'SE_A10032_006', 'SE_A10032_007', 'SE_A10032_008', 'SE_A10032_009', 'SE_A10032_010', 'SE_A10032_011', 'SE_A10032_012', 'SE_A10062B_001', 'SE_A10062B_002', 'SE_A10062B_003', 'SE_A10062B_004', 'SE_A10062B_005', 'SE_A10062B_006', 'SE_A18002_001', 'SE_A18002_002', 'SE_A18002_003', 'SE_A18002_004', 'SE_A18002_005', 'SE_A18002_006', 'SE_B18002_001', 'SE_B18002_002', 'SE_B18002_003', 'SE_A10039B_001', 'SE_A10039B_002', 'SE_A10039B_003', 'SE_A10039B_004', 'SE_A10039B_005', 'SE_A10039B_006', 'SE_A10039B_007', 'SE_A10039B_008', 'SE_A10039B_009', 'SE_A10039B_010', 'SE_A10039B_011', 'SE_A10039B_012', 'SE_A10039B_013', 'SE_A10039B_014', 'SE_A10039B_015', 'SE_A10039B_016', 'SE_A10039B_017', 'SE_A10039B_018', 'SE_A10039B_019', 'SE_A10039B_020', 'SE_A10039B_021', 'SE_A10039B_022', 'SE_A10039B_023', 'SE_A13003B_001', 'SE_A13003B_002', 'SE_A13003B_003']

In [5]:
data2 = data[["Geo_FIPS", "Geo_NAME", "SE_A00001_001", "SE_A14006_001", "SE_A10032_001", "SE_A18002_001", "SE_A10062B_001", 
              "SE_B18002_002", "SE_B18002_003", "SE_A13003B_001", "SE_A13003B_002", "SE_A14028_001"]]

In [6]:
data2.rename(columns = {"Geo_FIPS": "geofips",
                        "SE_A00001_001": "totpop", #total population
                        "SE_A14006_001": "mhhinc", #median household income
                        "SE_A10032_001":"housingunits", #number of housing units
                        "SE_A18002_001": "renterhousingunits", #numbre of renter housing units"
                        "SE_A10062B_001": "poprenterhousing", #population in household renter units
                        "SE_B18002_002": "rent30_49inc", 
                        "SE_B18002_003": "rent50plusinc", 
                        "SE_A13003B_001": "poppovertystatus", 
                        "SE_A13003B_002": "pop18_64poverty",
                        "SE_A14028_001": "gini"}, inplace = True)

data2["Year"] = year

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\rivera30\AppData\Local\Temp/ipykernel_43300/1657530488.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Year"] = year

In [7]:
data2.head()

,geofips,Geo_NAME,totpop,mhhinc,housingunits,renterhousingunits,poprenterhousing,rent30_49inc,rent50plusinc,poppovertystatus,pop18_64poverty,gini,Year
0,1001,"Autauga County, Alabama",55036,55317,23152,5624,14567,1280,1478,33451,4297,0.4501,2017
1,1003,"Baldwin County, Alabama",203360,52562,110023,20663,51150,4459,4335,117805,13777,0.4618,2017
2,1005,"Barbour County, Alabama",26201,33368,11918,3446,9102,633,727,13453,3153,0.4622,2017
3,1007,"Bibb County, Alabama",22580,43404,9112,1704,5217,363,342,12617,1591,0.4518,2017
4,1009,"Blount County, Alabama",57667,47412,24161,4444,11358,746,593,33919,4553,0.4302,2017

In [9]:
for year in range(2017, 2021):
    filename = "/1_raw/census_acs/acs_"+str(year)+".csv"
    data = pd.read_csv(fp+filename)
    
    data2 = data[["Geo_FIPS", "Geo_NAME", "SE_A00001_001", "SE_A14006_001", "SE_A10032_001", "SE_A18002_001", "SE_A10062B_001", 
              "SE_B18002_002", "SE_B18002_003", "SE_A13003B_001", "SE_A13003B_002", "SE_A14028_001"]]
    
    data2.rename(columns = {"Geo_FIPS": "geofips",
                        "SE_A00001_001": "totpop",
                        "SE_A14006_001": "mhhinc", 
                        "SE_A10032_001":"housingunits",
                        "SE_A18002_001": "renterhousingunits",
                        "SE_A10062B_001": "poprenterhousing", 
                        "SE_B18002_002": "rent30_49inc", 
                        "SE_B18002_003": "rent50plusinc", 
                        "SE_A13003B_001": "poppovertystatus", 
                        "SE_A13003B_002": "pop18_64poverty",
                        "SE_A14028_001": "gini"}, inplace = True)
    
    data2["Year"] = year
    

    # Write to a csv file
    data2.to_csv(fp+"/2_intermediate/census_acs/"+"ACSclean_"+str(year)+".csv")

    print("Done!")

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\rivera30\AppData\Local\Temp/ipykernel_43300/2084310014.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["Year"] = year

Done!
Done!
Done!
Done!

In [10]:
all_files = glob.glob(os.path.join(fp+"/2_intermediate/census_acs/", "*.csv"))     # advisable to use os.path.join as this makes concatenation OS independent
df_from_each_file = (pd.read_csv(f) for f in all_files)
concatenated_acs   = pd.concat(df_from_each_file, ignore_index=True)
concatenated_acs.head()

,Unnamed: 0,geofips,Geo_NAME,totpop,mhhinc,housingunits,renterhousingunits,poprenterhousing,rent30_49inc,rent50plusinc,poppovertystatus,pop18_64poverty,gini,Year
0,0,1001,"Autauga County, Alabama",55036,55317.0,23152,5624.0,14567,1280.0,1478.0,33451.0,4297.0,0.4501,2017
1,1,1003,"Baldwin County, Alabama",203360,52562.0,110023,20663.0,51150,4459.0,4335.0,117805.0,13777.0,0.4618,2017
2,2,1005,"Barbour County, Alabama",26201,33368.0,11918,3446.0,9102,633.0,727.0,13453.0,3153.0,0.4622,2017
3,3,1007,"Bibb County, Alabama",22580,43404.0,9112,1704.0,5217,363.0,342.0,12617.0,1591.0,0.4518,2017
4,4,1009,"Blount County, Alabama",57667,47412.0,24161,4444.0,11358,746.0,593.0,33919.0,4553.0,0.4302,2017

In [11]:
list(concatenated_acs.columns)

['Unnamed: 0',
 'geofips',
 'Geo_NAME',
 'totpop',
 'mhhinc',
 'housingunits',
 'renterhousingunits',
 'poprenterhousing',
 'rent30_49inc',
 'rent50plusinc',
 'poppovertystatus',
 'pop18_64poverty',
 'gini',
 'Year']

In [12]:
concatenated_acs.to_csv(fp+"/2_intermediate/"+"acs_2017_2020"+".csv")