In [1]:
import pandas as pd
import numpy as np
import os
import glob
import requests
import json
import ijson
from sodapy import Socrata

In [2]:
#os. getcwd()

In [3]:
fp = r"..\\data"

# Vaccinations data

## COVID-19 Vaccinations in the US by county
Source: https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh/about_data

In [4]:
app_token = 'A11ReB7HpqzRTafJo2y6FreNs'
api_secret = '3iv2k8t6930oy7jq0z9kabaix7n1wsrluq4pn15ogoa64lc6pa'

socrata_domain = 'data.cdc.gov'
socrata_dataset_identifier = '8xkx-amqh'

client = Socrata(
    socrata_domain,
    app_token,
    timeout=100
)

In [5]:
client.get_metadata("8xkx-amqh")

{'id': '8xkx-amqh',
 'name': 'COVID-19 Vaccinations in the United States,County',
 'assetType': 'dataset',
 'attribution': 'IISInfo',
 'averageRating': 0,
 'category': 'Vaccinations',
 'createdAt': 1621883212,
 'description': 'Overall US COVID-19 Vaccine administration and vaccine equity data at county level. Data represents all vaccine partners including jurisdictional partner clinics, retail pharmacies, long-term care facilities, dialysis centers, Federal Emergency Management Agency and Health Resources and Services Administration partner sites, and federal entity facilities.\xa0',
 'displayType': 'table',
 'downloadCount': 221772,
 'hideFromCatalog': False,
 'hideFromDataJson': False,
 'licenseId': 'USGOV_WORKS',
 'locked': False,
 'newBackend': True,
 'numberOfComments': 2,
 'oid': 39112692,
 'provenance': 'official',
 'publicationAppendEnabled': False,
 'publicationDate': 1670554492,
 'publicationGroup': 18329577,
 'publicationStage': 'published',
 'rowsUpdatedAt': 1683870371,
 'rowsUpdatedBy': '3suw-ciyu',
 'tableId': 18985799,
 'totalTimesRated': 0,
 'viewCount': 475616,
 'viewLastModified': 1683869775,
 'viewType': 'tabular',
 'approvals': [{'reviewedAt': 1643066183,
   'reviewedAutomatically': True,
   'state': 'approved',
   'submissionId': 5152002,
   'submissionObject': 'public_audience_request',
   'submissionOutcome': 'change_audience',
   'submittedAt': 1643066183,
   'targetAudience': 'public',
   'workflowId': 2100,
   'submissionDetails': {'permissionType': 'READ'},
   'submissionOutcomeApplication': {'endedAt': 1643066183,
    'failureCount': 0,
    'startedAt': 1643066183,
    'status': 'success'},
   'submitter': {'id': '3suw-ciyu', 'displayName': 'NCIRD'}}],
 'clientContext': {'clientContextVariables': [], 'inheritedVariables': {}},
 'columns': [{'id': 568832800,
   'name': 'Date',
   'dataTypeName': 'calendar_date',
   'description': 'Date data are reported on CDC COVID Data Tracker',
   'fieldName': 'date',
   'position': 1,
   'renderTypeName': 'calendar_date',
   'tableColumnId': 138084955,
   'cachedContents': {'non_null': '1962781',
    'largest': '2023-05-10T00:00:00.000',
    'null': '0',
    'top': [{'item': '2022-04-27T00:00:00.000', 'count': '3284'},
     {'item': '2022-04-28T00:00:00.000', 'count': '3284'},
     {'item': '2022-04-29T00:00:00.000', 'count': '3284'},
     {'item': '2022-04-30T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-01T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-02T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-03T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-04T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-05T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-06T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-07T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-08T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-09T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-10T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-11T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-12T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-13T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-14T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-15T00:00:00.000', 'count': '3284'},
     {'item': '2022-05-16T00:00:00.000', 'count': '3284'}],
    'smallest': '2020-12-13T00:00:00.000',
    'count': '1962781',
    'cardinality': '598'},
   'format': {'view': 'date'}},
  {'id': 568832801,
   'name': 'FIPS',
   'dataTypeName': 'text',
   'description': 'Federal Information Processing Standard State Code',
   'fieldName': 'fips',
   'position': 2,
   'renderTypeName': 'text',
   'tableColumnId': 138084954,
   'cachedContents': {'non_null': '1962781',
    'largest': 'UNK',
    'null': '0',
    'top': [{'item': 'UNK', 'count': '34829'},
     {'item': '01005', 'count': '598'},
     {'item': '13253', 'count': '598'},
     {'item': '01009', 'count': '598'},
     {'item': '01011', 'count': '598'},
     {'item': '01013', 'count': '598'},
     {'item': '08021', 'count': '598'},
     {'item': '01017', 'count': '598'},
     {'item': '01019', 'count': '598'},
     {'item': '01021', 'count': '598'},
     {'item': '01023', 'count': '598'},
     {'item': '01025', 'count': '598'},
     {'item': '01027', 'count': '598'},
     {'item': '01029', 'count': '598'},
     {'item': '05033', 'count': '598'},
     {'item': '01033', 'count': '598'},
     {'item': '01035', 'count': '598'},
     {'item': '01037', 'count': '598'},
     {'item': '01039', 'count': '598'},
     {'item': '01041', 'count': '598'}],
    'smallest': '01001',
    'count': '1962781',
    'cardinality': '3225'},
   'format': {}},
  {'id': 568832802,
   'name': 'MMWR_week',
   'dataTypeName': 'number',
   'description': 'MMWR Week',
   'fieldName': 'mmwr_week',
   'position': 3,
   'renderTypeName': 'number',
   'tableColumnId': 138084953,
   'cachedContents': {'non_null': '1962781',
    'largest': '53',
    'null': '0',
    'top': [{'item': '1', 'count': '52521'},
     {'item': '19', 'count': '49245'},
     {'item': '18', 'count': '49245'},
     {'item': '17', 'count': '49245'},
     {'item': '16', 'count': '49245'},
     {'item': '15', 'count': '49245'},
     {'item': '14', 'count': '49243'},
     {'item': '8', 'count': '49238'},
     {'item': '9', 'count': '49238'},
     {'item': '10', 'count': '49238'},
     {'item': '11', 'count': '49238'},
     {'item': '7', 'count': '49238'},
     {'item': '6', 'count': '49238'},
     {'item': '4', 'count': '49238'},
     {'item': '5', 'count': '49238'},
     {'item': '2', 'count': '49238'},
     {'item': '12', 'count': '49235'},
     {'item': '13', 'count': '49231'},
     {'item': '52', 'count': '49223'},
     {'item': '51', 'count': '49046'}],
    'smallest': '1',
    'count': '1962781',
    'cardinality': '53'},
   'format': {}},
  {'id': 568832803,
   'name': 'Recip_County',
   'dataTypeName': 'text',
   'description': 'County of residence',
   'fieldName': 'recip_county',
   'position': 4,
   'renderTypeName': 'text',
   'tableColumnId': 138084952,
   'cachedContents': {'non_null': '1962781',
    'largest': 'Ziebach County',
    'null': '0',
    'top': [{'item': 'Unknown County', 'count': '34829'},
     {'item': 'Washington County', 'count': '17940'},
     {'item': 'Jefferson County', 'count': '14950'},
     {'item': 'Franklin County', 'count': '14352'},
     {'item': 'Lincoln County', 'count': '13754'},
     {'item': 'Jackson County', 'count': '13754'},
     {'item': 'Madison County', 'count': '11362'},
     {'item': 'Clay County', 'count': '10764'},
     {'item': 'Montgomery County', 'count': '10764'},
     {'item': 'Union County', 'count': '10166'},
     {'item': 'Marion County', 'count': '10166'},
     {'item': 'Monroe County', 'count': '10166'},
     {'item': 'Wayne County', 'count': '9568'},
     {'item': 'Warren County', 'count': '8372'},
     {'item': 'Grant County', 'count': '8372'},
     {'item': 'Greene County', 'count': '8372'},
     {'item': 'Carroll County', 'count': '7774'},
     {'item': 'Clark County', 'count': '7176'},
     {'item': 'Lake County', 'count': '7176'},
     {'item': 'Adams County', 'count': '7176'}],
    'smallest': 'Abbeville County',
    'count': '1962781',
    'cardinality': '1960'},
   'format': {}},
  {'id': 568832804,
   'name': 'Recip_State',
   'dataTypeName': 'text',
   'description': 'Recipient State',
   'fieldName': 'recip_state',
   'position': 5,
   'renderTypeName': 'text',
   'tableColumnId': 138084951,
   'cachedContents': {'non_null': '1962700',
    'largest': 'WY',
    'null': '81',
    'top': [{'item': 'TX', 'count': '152177'},
     {'item': 'GA', 'count': '95677'},
     {'item': 'VA', 'count': '80130'},
     {'item': 'KY', 'count': '72356'},
     {'item': 'MO', 'count': '69365'},
     {'item': 'KS', 'count': '63385'},
     {'item': 'IL', 'count': '61592'},
     {'item': 'NC', 'count': '60396'},
     {'item': 'IA', 'count': '59797'},
     {'item': 'TN', 'count': '57405'},
     {'item': 'NE', 'count': '56209'},
     {'item': 'IN', 'count': '55611'},
     {'item': 'OH', 'count': '53219'},
     {'item': 'MN', 'count': '52622'},
     {'item': 'MI', 'count': '50230'},
     {'item': 'MS', 'count': '49631'},
     {'item': 'PR', 'count': '47238'},
     {'item': 'OK', 'count': '46641'},
     {'item': 'AR', 'count': '45445'},
     {'item': 'WI', 'count': '43652'}],
    'smallest': 'AK',
    'count': '1962781',
    'cardinality': '60'},
   'format': {}},
  {'id': 568832805,
   'name': 'Completeness_pct',
   'dataTypeName': 'number',
   'description': 'Represents the proportion of people with a completed primary series whose Federal Information Processing Standards (FIPS) code is reported and matches a valid county FIPS code in the jurisdiction.\xa0\xa0',
   'fieldName': 'completeness_pct',
   'position': 6,
   'renderTypeName': 'number',
   'tableColumnId': 138084942,
   'cachedContents': {'non_null': '1957108',
    'largest': '100',
    'null': '5673',
    'top': [{'item': '0', 'count': '206776'},
     {'item': '97.8', 'count': '58164'},
     {'item': '98.6', 'count': '56401'},
     {'item': '97.4', 'count': '48094'},
     {'item': '97.6', 'count': '47202'},
     {'item': '98.7', 'count': '45926'},
     {'item': '97.5', 'count': '37539'},
     {'item': '98.9', 'count': '36644'},
     {'item': '94', 'count': '33915'},
     {'item': '98.3', 'count': '32684'},
     {'item': '97.1', 'count': '32393'},
     {'item': '93.6', 'count': '30363'},
     {'item': '97.3', 'count': '29755'},
     {'item': '97.7', 'count': '28610'},
     {'item': '97.9', 'count': '28428'},
     {'item': '96.8', 'count': '28119'},
     {'item': '96.9', 'count': '26723'},
     {'item': '99.1', 'count': '25769'},
     {'item': '98.1', 'count': '25665'},
     {'item': '91.3', 'count': '25012'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '616'},
   'format': {}},
  {'id': 568832806,
   'name': 'Administered_Dose1_Recip',
   'dataTypeName': 'number',
   'description': 'People with at least one Dose by State of Residence',
   'fieldName': 'administered_dose1_recip',
   'position': 7,
   'renderTypeName': 'number',
   'tableColumnId': 140505246,
   'cachedContents': {'non_null': '1904494',
    'largest': '8444862',
    'null': '58287',
    'top': [{'item': '0', 'count': '203648'},
     {'item': '527', 'count': '209'},
     {'item': '804', 'count': '206'},
     {'item': '1161', 'count': '201'},
     {'item': '513', 'count': '195'},
     {'item': '1452', 'count': '195'},
     {'item': '240', 'count': '194'},
     {'item': '772', 'count': '192'},
     {'item': '1244', 'count': '189'},
     {'item': '1117', 'count': '185'},
     {'item': '861', 'count': '184'},
     {'item': '620', 'count': '183'},
     {'item': '1189', 'count': '182'},
     {'item': '1113', 'count': '182'},
     {'item': '1150', 'count': '180'},
     {'item': '763', 'count': '179'},
     {'item': '423', 'count': '179'},
     {'item': '1142', 'count': '178'},
     {'item': '1326', 'count': '176'},
     {'item': '994', 'count': '176'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '251698'},
   'format': {}},
  {'id': 568832807,
   'name': 'Administered_Dose1_Pop_Pct',
   'dataTypeName': 'number',
   'description': 'Percent of Total Pop with at least one Dose by State of Residence',
   'fieldName': 'administered_dose1_pop_pct',
   'position': 8,
   'renderTypeName': 'number',
   'tableColumnId': 140505248,
   'cachedContents': {'non_null': '1938696',
    'largest': '100',
    'null': '24085',
    'top': [{'item': '0', 'count': '272965'},
     {'item': '95', 'count': '18340'},
     {'item': '47.4', 'count': '4065'},
     {'item': '47.5', 'count': '3921'},
     {'item': '47.6', 'count': '3916'},
     {'item': '47.8', 'count': '3877'},
     {'item': '48.6', 'count': '3865'},
     {'item': '46.6', 'count': '3863'},
     {'item': '50.5', 'count': '3863'},
     {'item': '46.3', 'count': '3841'},
     {'item': '46.2', 'count': '3839'},
     {'item': '49', 'count': '3836'},
     {'item': '45.2', 'count': '3829'},
     {'item': '44.9', 'count': '3822'},
     {'item': '47.7', 'count': '3800'},
     {'item': '51.5', 'count': '3796'},
     {'item': '50.8', 'count': '3796'},
     {'item': '54.4', 'count': '3795'},
     {'item': '48.3', 'count': '3794'},
     {'item': '47.2', 'count': '3793'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '1001'},
   'format': {}},
  {'id': 568832808,
   'name': 'Administered_Dose1_Recip_5Plus',
   'dataTypeName': 'number',
   'description': 'Total number of people 5+ with at least one dose based on the jurisdiction where recipient lives',
   'fieldName': 'administered_dose1_recip_5plus',
   'position': 9,
   'renderTypeName': 'number',
   'tableColumnId': 140505251,
   'cachedContents': {'non_null': '747170',
    'largest': '8372986',
    'null': '1215611',
    'top': [{'item': '0', 'count': '2070'},
     {'item': '1242', 'count': '126'},
     {'item': '1863', 'count': '111'},
     {'item': '251', 'count': '111'},
     {'item': '513', 'count': '110'},
     {'item': '278', 'count': '100'},
     {'item': '2142', 'count': '100'},
     {'item': '527', 'count': '97'},
     {'item': '423', 'count': '96'},
     {'item': '108', 'count': '96'},
     {'item': '3669', 'count': '96'},
     {'item': '1444', 'count': '95'},
     {'item': '1113', 'count': '93'},
     {'item': '240', 'count': '92'},
     {'item': '763', 'count': '92'},
     {'item': '45', 'count': '91'},
     {'item': '1142', 'count': '88'},
     {'item': '1410', 'count': '85'},
     {'item': '368', 'count': '84'},
     {'item': '1304', 'count': '83'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '178897'},
   'format': {}},
  {'id': 568832809,
   'name': 'Administered_Dose1_Recip_5PlusPop_Pct',
   'dataTypeName': 'number',
   'description': 'Percent of 5+ population with at least one dose based on the jurisdiction where recipient lives',
   'fieldName': 'administered_dose1_recip_5pluspop_pct',
   'position': 10,
   'renderTypeName': 'number',
   'tableColumnId': 140505265,
   'cachedContents': {'non_null': '751950',
    'largest': '99.9',
    'null': '1210831',
    'top': [{'item': '95', 'count': '31113'},
     {'item': '0', 'count': '20922'},
     {'item': '57.2', 'count': '2259'},
     {'item': '58.1', 'count': '2247'},
     {'item': '59.5', 'count': '2231'},
     {'item': '57.1', 'count': '2206'},
     {'item': '59.7', 'count': '2203'},
     {'item': '57.9', 'count': '2201'},
     {'item': '57.4', 'count': '2185'},
     {'item': '57.5', 'count': '2183'},
     {'item': '59.9', 'count': '2178'},
     {'item': '59.2', 'count': '2177'},
     {'item': '59.6', 'count': '2166'},
     {'item': '57', 'count': '2164'},
     {'item': '56.1', 'count': '2163'},
     {'item': '60.4', 'count': '2159'},
     {'item': '53.9', 'count': '2147'},
     {'item': '60.1', 'count': '2144'},
     {'item': '55', 'count': '2143'},
     {'item': '57.7', 'count': '2133'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '881'},
   'format': {}},
  {'id': 568832810,
   'name': 'Administered_Dose1_Recip_12Plus',
   'dataTypeName': 'number',
   'description': 'People 12+ with at least one Dose by State of Residence',
   'fieldName': 'administered_dose1_recip_12plus',
   'position': 11,
   'renderTypeName': 'number',
   'tableColumnId': 140505250,
   'cachedContents': {'non_null': '1845201',
    'largest': '7982095',
    'null': '117580',
    'top': [{'item': '0', 'count': '201775'},
     {'item': '1222', 'count': '240'},
     {'item': '798', 'count': '221'},
     {'item': '245', 'count': '196'},
     {'item': '1150', 'count': '190'},
     {'item': '421', 'count': '181'},
     {'item': '1268', 'count': '181'},
     {'item': '1126', 'count': '177'},
     {'item': '1317', 'count': '177'},
     {'item': '1420', 'count': '175'},
     {'item': '1114', 'count': '175'},
     {'item': '876', 'count': '174'},
     {'item': '1071', 'count': '173'},
     {'item': '755', 'count': '173'},
     {'item': '1524', 'count': '172'},
     {'item': '1843', 'count': '172'},
     {'item': '749', 'count': '170'},
     {'item': '984', 'count': '169'},
     {'item': '648', 'count': '169'},
     {'item': '858', 'count': '168'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '247499'},
   'format': {}},
  {'id': 568832811,
   'name': 'Administered_Dose1_Recip_12PlusPop_Pct',
   'dataTypeName': 'number',
   'description': 'Percent of 12+ Pop with at least one Dose by State of Residence',
   'fieldName': 'administered_dose1_recip_12pluspop_pct',
   'position': 12,
   'renderTypeName': 'number',
   'tableColumnId': 140505244,
   'cachedContents': {'non_null': '1914183',
    'largest': '100.0',
    'null': '48598',
    'top': [{'item': '0', 'count': '304225'},
     {'item': '95', 'count': '43975'},
     {'item': '55.4', 'count': '3505'},
     {'item': '57.7', 'count': '3484'},
     {'item': '57.5', 'count': '3456'},
     {'item': '54.5', 'count': '3423'},
     {'item': '58.9', 'count': '3389'},
     {'item': '57.8', 'count': '3379'},
     {'item': '53.8', 'count': '3368'},
     {'item': '55.2', 'count': '3365'},
     {'item': '55.9', 'count': '3344'},
     {'item': '58', 'count': '3344'},
     {'item': '55', 'count': '3339'},
     {'item': '58.1', 'count': '3339'},
     {'item': '63', 'count': '3338'},
     {'item': '54.2', 'count': '3331'},
     {'item': '54.3', 'count': '3327'},
     {'item': '53.9', 'count': '3326'},
     {'item': '99.9', 'count': '3324'},
     {'item': '61.9', 'count': '3323'}],
    'smallest': '0.0',
    'count': '1962781',
    'cardinality': '1001'},
   'format': {}},
  {'id': 568832812,
   'name': 'Administered_Dose1_Recip_18Plus',
   'dataTypeName': 'number',
   'description': 'People 18+ with at least one Dose by State of Residence',
   'fieldName': 'administered_dose1_recip_18plus',
   'position': 13,
   'renderTypeName': 'number',
   'tableColumnId': 140505243,
   'cachedContents': {'non_null': '1863398',
    'largest': '7323682',
    'null': '99383',
    'top': [{'item': '0', 'count': '203648'},
     {'item': '1176', 'count': '217'},
     {'item': '219', 'count': '214'},
     {'item': '780', 'count': '209'},
     {'item': '1108', 'count': '209'},
     {'item': '670', 'count': '202'},
     {'item': '362', 'count': '198'},
     {'item': '1182', 'count': '197'},
     {'item': '820', 'count': '194'},
     {'item': '1440', 'count': '190'},
     {'item': '237', 'count': '187'},
     {'item': '818', 'count': '186'},
     {'item': '292', 'count': '185'},
     {'item': '489', 'count': '181'},
     {'item': '817', 'count': '179'},
     {'item': '2048', 'count': '179'},
     {'item': '268', 'count': '178'},
     {'item': '234', 'count': '178'},
     {'item': '976', 'count': '177'},
     {'item': '1284', 'count': '177'}],
    'smallest': '0',
    'count': '1962781',
    'cardinality': '241608'},
   'format': {}},
  {'id': 568832813,
   'name': 'Administered_Dose1_Recip_18PlusPop_Pct',
   'dataTypeName': 'number',
   'description': 'Percent of 18+ Pop with at least one Dose by State of Residence',
   'fieldName': 'administered_dose1_recip_18pluspop_pct',
   'position': 14,
   'renderTypeName': 'number',
   'tableColumnId': 140505239,
   'cachedContents': {'non_null': '1932579',
    'largest': '100',
    'null': '30202',
    'top': [{'item': '0', 'count': '306166'},
     {'item': '95', 'count': '48937'},
     {'item': '99.9', 'count': '3592'},
     {'item': '59.4', 'count': '3555'},
     {'item': '59.2', 'count': '3553'},
     {'item': '56.9', 'count': '3545'},
     {'item': '59.5', 'count': '3539'},
     {'item': '59', 'count': '3499'},
     {'item': '56.8', 'count': '3497'},
     {'item': '56.7', 'count': '3494'},
     {'item': '58.7', 'count': '3485'},
     {'item': '67.2', 'count': '3478'},
     {'item': '60.9', 'count': '3478'},
     {'item': '61.3', 'count': '3473'},
     {'item': '57.3', 'count': '3466'},
     {'item': '66.8', 'count': '3456'},

In [6]:
query = """
SELECT 
    * 
WHERE 
    date < '2025-01'
LIMIT 
    600000000
"""

In [7]:
results = client.get(
    socrata_dataset_identifier,
    query=query)
client.close()

In [8]:
#results = client.get_all("8xkx-amqh")
#client.close()

In [9]:
vacccines = pd.DataFrame.from_records(results)

In [10]:
vacccines.head()

,date,fips,mmwr_week,recip_county,recip_state,completeness_pct,administered_dose1_recip,administered_dose1_pop_pct,administered_dose1_recip_5plus,administered_dose1_recip_5pluspop_pct,...,census2019_18pluspop,census2019_65pluspop,bivalent_booster_5plus,bivalent_booster_5plus_pop_pct,bivalent_booster_12plus,bivalent_booster_12plus_pop_pct,bivalent_booster_18plus,bivalent_booster_18plus_pop_pct,bivalent_booster_65plus,bivalent_booster_65plus_pop_pct
0,2023-05-10T00:00:00.000,55129,19,Washburn County,WI,96.7,11123,70.8,11097,73.9,...,12758,4304,3978,26.5,3955,28.6,3899,30.6,2588,60.1
1,2023-05-10T00:00:00.000,19173,19,Taylor County,IA,97.3,3149,51.4,3145,55,...,4687,1392,841,14.7,841,16.3,834,17.8,588,42.2
2,2023-05-10T00:00:00.000,36059,19,Nassau County,NY,97.5,1391226,95,1384503,95,...,1065968,246690,236202,18.4,231748,19.8,224931,21.1,109947,44.6
3,2023-05-10T00:00:00.000,48281,19,Lampasas County,TX,98.9,11678,54.5,11660,57.4,...,16799,4322,1951,9.6,1947,10.5,1925,11.5,1229,28.4
4,2023-05-10T00:00:00.000,26145,19,Saginaw County,MI,94,104075,54.6,NaN,NaN,...,149676,37414,15618,8.7,15448,9.4,15112,10.1,7921,21.2

In [11]:
#vacccines.to_csv(fp+"/2_intermediate/"+"vaccinations_dec2020_may2023"+".csv")

vacccines.to_stata(fp+"/2_intermediate/"+"vaccinations_dec2020_may2023"+".dta")

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\io\stata.py:2397: InvalidColumnName:
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    administered_dose1_recip_5pluspop_pct   ->   administered_dose1_recip_5pluspo
    administered_dose1_recip_12pluspop_pct   ->   administered_dose1_recip_12plusp
    administered_dose1_recip_18pluspop_pct   ->   administered_dose1_recip_18plusp
    administered_dose1_recip_65pluspop_pct   ->   administered_dose1_recip_65plusp
    series_complete_12pluspop_pct_svi   ->   series_complete_12pluspop_pct_sv
    series_complete_18pluspop_pct_svi   ->   series_complete_18pluspop_pct_sv
    series_complete_65pluspop_pct_svi   ->   series_complete_65pluspop_pct_sv
    series_complete_pop_pct_ur_equity   ->   series_complete_pop_pct_ur_equit
    series_complete_5pluspop_pct_ur_equity   ->   series_complete_5pluspop_pct_ur_
    series_complete_5to17pop_pct_ur_equity   ->   series_complete_5to17pop_pct_ur_
    series_complete_12pluspop_pct_ur_equity   ->   series_complete_12pluspop_pct_ur
    series_complete_18pluspop_pct_ur_equity   ->   series_complete_18pluspop_pct_ur
    series_complete_65pluspop_pct_ur_equity   ->   series_complete_65pluspop_pct_ur
    booster_doses_12plusvax_pct_ur_equity   ->   booster_doses_12plusvax_pct_ur_e
    booster_doses_18plusvax_pct_ur_equity   ->   booster_doses_18plusvax_pct_ur_e
    booster_doses_65plusvax_pct_ur_equity   ->   booster_doses_65plusvax_pct_ur_e

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  warnings.warn(ws, InvalidColumnName)

In [12]:
query = """
SELECT 
    * 
WHERE 
    date < '2022-01'
LIMIT 
    600000000
"""

In [13]:
results = client.get(
    socrata_dataset_identifier,
    query=query)
client.close()

In [14]:
vacccines2020_2021 = pd.DataFrame.from_records(results)

In [15]:
vacccines2020_2021

,date,fips,mmwr_week,recip_county,recip_state,completeness_pct,administered_dose1_recip,administered_dose1_pop_pct,administered_dose1_recip_12plus,administered_dose1_recip_12pluspop_pct,...,census2019_5pluspop,booster_doses,booster_doses_vax_pct,booster_doses_18plus,booster_doses_18plus_vax_pct,booster_doses_50plus,booster_doses_50plus_vax_pct,booster_doses_65plus,booster_doses_65plus_vax_pct,census2019_65pluspop
0,2020-12-13T00:00:00.000,48353,51,Nolan County,TX,0,0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-12-13T00:00:00.000,40117,51,Pawnee County,OK,0,0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-12-13T00:00:00.000,18139,51,Rush County,IN,0,0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-12-13T00:00:00.000,47047,51,Fayette County,TN,0,0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-12-13T00:00:00.000,29049,51,Clinton County,MO,0,0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1260144,2021-12-31T00:00:00.000,42029,52,Chester County,PA,94.6,489163,93.2,468818,95.0,...,496254,115831,30.2,114520,33.8,80643,44.6,46605,54.4,88351
1260145,2021-12-31T00:00:00.000,17001,52,Adams County,IL,98,36183,55.3,35641,64.1,...,61336,12249,36.8,12203,38.8,10122,50.8,7233,64.5,13513
1260146,2021-12-31T00:00:00.000,48099,52,Coryell County,TX,99.1,39550,52.1,38957,61.0,...,70826,8332,24.4,8297,26.0,6138,37.9,3771,46.5,8040
1260147,2021-12-31T00:00:00.000,18081,52,Johnson County,IN,98.6,100092,63.3,96729,72.8,...,148304,29907,33.9,29594,36.6,20863,48.3,12660,58.8,23480
1260148,2021-12-31T00:00:00.000,41047,52,Marion County,OR,97.8,230278,66.2,223967,76.8,...,325089,71891,34.6,71414,37.8,50698,53.2,32257,65.6,56279

In [16]:
vacccines2020_2021.to_stata(fp+"/2_intermediate/"+"vaccinatons_2020_2021"+".dta")

C:\Users\rivera30\Anaconda3\lib\site-packages\pandas\io\stata.py:2397: InvalidColumnName:
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    administered_dose1_recip_12pluspop_pct   ->   administered_dose1_recip_12plusp
    administered_dose1_recip_18pluspop_pct   ->   administered_dose1_recip_18plusp
    administered_dose1_recip_65pluspop_pct   ->   administered_dose1_recip_65plusp
    series_complete_12pluspop_pct_svi   ->   series_complete_12pluspop_pct_sv
    series_complete_18pluspop_pct_svi   ->   series_complete_18pluspop_pct_sv
    series_complete_65pluspop_pct_svi   ->   series_complete_65pluspop_pct_sv
    series_complete_pop_pct_ur_equity   ->   series_complete_pop_pct_ur_equit
    series_complete_12pluspop_pct_ur_equity   ->   series_complete_12pluspop_pct_ur
    series_complete_18pluspop_pct_ur_equity   ->   series_complete_18pluspop_pct_ur
    series_complete_65pluspop_pct_ur_equity   ->   series_complete_65pluspop_pct_ur
    administered_dose1_recip_5pluspop_pct   ->   administered_dose1_recip_5pluspo
    series_complete_5pluspop_pct_ur_equity   ->   series_complete_5pluspop_pct_ur_

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  warnings.warn(ws, InvalidColumnName)

In [17]:
socrata_domain = 'data.cdc.gov'
socrata_dataset_identifier = '8396-v7yb'

client = Socrata(
    socrata_domain,
    app_token,
    timeout=100
)

In [18]:
#client.get_metadata("jgk8-6dpn")
#client.get_metadata("dt66-w6m6")

socrata_dataset_identifier = 'nra9-vzzn'

client.get_metadata("nra9-vzzn")

{'id': 'nra9-vzzn',
 'name': 'United States COVID-19 County Level of Community Transmission Historical Changes - ARCHIVED',
 'assetType': 'dataset',
 'attribution': 'CDC COVID-19 Response',
 'attributionLink': 'https://covid.cdc.gov/covid-data-tracker/#county-view',
 'averageRating': 0,
 'category': 'Public Health Surveillance',
 'createdAt': 1628264443,
 'description': 'On October 20, 2022, CDC began retrieving aggregate case and death data from jurisdictional and state partners weekly instead of daily. This dataset contains archived historical community transmission and related data elements by county. Although these data will continue to be publicly available, this dataset has not been updated since October 20, 2022. An archived dataset containing weekly historical community transmission data by county can also be found here: <a href="https://data.cdc.gov/Public-Health-Surveillance/Weekly-COVID-19-County-Level-of-Community-Transmis/jgk8-6dpn">Weekly COVID-19 County Level of Community Transmission Historical Changes | Data | Centers for Disease Control and Prevention (cdc.gov)</a>. \n\n<b>Related data</b>\nCDC has been providing the public with two versions of COVID-19 county-level community transmission level data: this historical dataset with the daily county-level transmission data from January 22, 2020, and a dataset with the daily values as originally posted on the COVID Data Tracker. Similar to this dataset, the <a href="https://data.cdc.gov/Public-Health-Surveillance/United-States-COVID-19-County-Level-of-Community-T/nra9-vzzn">original dataset</a> with daily data as posted is archived on 10/20/2022. It will continue to be publicly available but will no longer be updated. A new dataset containing community transmission data by county as originally posted is now published weekly and can be found at: <a href="https://data.cdc.gov/dataset/Weekly-COVID-19-County-Level-of-Community-Transmis/dt66-w6m6">Weekly COVID-19 County Level of Community Transmission as Originally Posted | Data | Centers for Disease Control and Prevention (cdc.gov)</a>.\n\nThis public use dataset has 7 data elements reflecting historical data for community transmission levels for all available counties and jurisdictions. It contains historical data for the county level of community transmission and includes updated data submitted by states and jurisdictions. Each day, the dataset was updated to include the most recent days’ data and incorporate any historical changes made by jurisdictions. This dataset includes data since January 22, 2020. Transmission level is set to low, moderate, substantial, or high using the calculation rules below.\n\n<b>Methods for calculating county level of community transmission indicator</b>\nThe County Level of Community Transmission indicator uses two metrics: (1) total new COVID-19 cases per 100,000 persons in the last 7 days and (2) percentage of positive SARS-CoV-2 diagnostic nucleic acid amplification tests (NAAT) in the last 7 days. For each of these metrics, CDC classifies transmission values as low, moderate, substantial, or high (below and <a href="https://www.cdc.gov/mmwr/volumes/70/wr/mm7030e2.htm?s_cid=mm7030e2_w#T1_down">here</a>). If the values for each of these two metrics differ (e.g., one indicates moderate and the other low), then the higher of the two should be used for decision-making.\n\n<b>CDC core metrics of and thresholds for community transmission levels of SARS-CoV-2</b>\n\n<b>Total New Case Rate Metric:</b> "New cases per 100,000 persons in the past 7 days" is calculated by adding the number of new cases in the county (or other administrative level) in the last 7 days divided by the population in the county (or other administrative level) and multiplying by 100,000. "New cases per 100,000 persons in the past 7 days" is considered to have transmission level of Low (0-9.99); Moderate (10.00-49.99); Substantial (50.00-99.99); and High (greater than or equal to 100.00).\n\n<b>Test Percent Positivity Metric:</b> "Percentage of positive NAAT in the past 7 days" is calculated by dividing the number of positive tests in the county (or other administrative level) during the last 7 days by the total number of tests resulted over the last 7 days. "Percentage of positive NAAT in the past 7 days" is considered to have transmission level of Low (less than 5.00); Moderate (5.00-7.99); Substantial (8.00-9.99); and High (greater than or equal to 10.00).\n\nIf the two metrics suggest different transmission levels, the higher level is selected. If one metric is missing, the other metric is used for the indicator.\n\nThe reported transmission categories include:\n\nLow Transmission Threshold: Counties with fewer than 10 total cases per 100,000 population in the past 7 days, and a NAAT percent test positivity in the past 7 days below 5%;\n\nModerate Transmission Threshold: Counties with 10-49 total cases per 100,000 population in the past 7 days or a NAAT test percent positivity in the past 7 days of 5.0-7.99%;\n\nSubstantial Transmission Threshold: Counties with 50-99 total cases per 100,000 population in the past 7 days or a NAAT test percent positivity in the past 7 days of 8.0-9.99%;\n\nHigh Transmission Threshold: Counties with 100 or more total cases per 100,000 population in the past 7 days or a NAAT test percent positivity in the past 7 days of 10.0% or greater.\n\nBlank: total new cases in the past 7 days are not reported (county data known to be unavailable) and the percentage of positive NAATs tests during the past 7 days (blank) are not reported.\n\n<b>Data Suppression</b>\nTo prevent the release of data that could be used to identify people, data cells are suppressed for low frequency. When the <b>case counts</b> used to calculate the total new case rate metric ("cases_per_100K_7_day_count_change") is greater than zero and less than 10, this metric is set to "suppressed" to protect individual privacy. If the case count is 0, the total new case rate metric is still displayed.\n\nThe data in this dataset are considered provisional by CDC and are subject to change until the data are reconciled and verified with the state and territorial data providers. This datasets are created using <a href="https://www.cdc.gov/maso/policy/policy385.pdf">CDC’s Policy on Public Health Research and Nonresearch Data Management and Access</a>.\n\n<b>Duplicate Records Issue</b>\nA bug was found on 12/28/2021 that caused many records in the dataset to be duplicated. This issue was resolved on 01/06/2022.',
 'displayType': 'table',
 'downloadCount': 32059,
 'hideFromCatalog': False,
 'hideFromDataJson': False,
 'licenseId': 'USGOV_WORKS',
 'locked': False,
 'newBackend': True,
 'numberOfComments': 0,
 'oid': 38070422,
 'provenance': 'official',
 'publicationAppendEnabled': False,
 'publicationDate': 1641495928,
 'publicationGroup': 18408605,
 'publicationStage': 'published',
 'rowsUpdatedAt': 1666314918,
 'rowsUpdatedBy': 'xkjz-754r',
 'tableId': 18548383,
 'totalTimesRated': 0,
 'viewCount': 59745,
 'viewLastModified': 1719584014,
 'viewType': 'tabular',
 'approvals': [{'reviewedAt': 1635441048,
   'reviewedAutomatically': True,
   'state': 'approved',
   'submissionId': 4334398,
   'submissionObject': 'public_audience_request',
   'submissionOutcome': 'change_audience',
   'submittedAt': 1635441048,
   'targetAudience': 'public',
   'workflowId': 2100,
   'submissionDetails': {'permissionType': 'READ'},
   'submissionOutcomeApplication': {'endedAt': 1635441048,
    'failureCount': 0,
    'startedAt': 1635441048,
    'status': 'success'},
   'submitter': {'id': 'aa26-iwd8', 'displayName': 'Brian Lee'}}],
 'clientContext': {'clientContextVariables': [], 'inheritedVariables': {}},
 'columns': [{'id': 553949578,
   'name': 'state_name',
   'dataTypeName': 'text',
   'description': 'State',
   'fieldName': 'state_name',
   'position': 1,
   'renderTypeName': 'text',
   'tableColumnId': 138989114,
   'cachedContents': {'non_null': '3222560',
    'largest': 'Wyoming',
    'null': '2662',
    'top': [{'item': 'Texas', 'count': '254000'},
     {'item': 'Georgia', 'count': '159000'},
     {'item': 'Virginia', 'count': '133000'},
     {'item': 'Kentucky', 'count': '120000'},
     {'item': 'Missouri', 'count': '115000'},
     {'item': 'Kansas', 'count': '105000'},
     {'item': 'Illinois', 'count': '102000'},
     {'item': 'North Carolina', 'count': '100000'},
     {'item': 'Iowa', 'count': '99099'},
     {'item': 'Tennessee', 'count': '95095'},
     {'item': 'Nebraska', 'count': '93000'},
     {'item': 'Indiana', 'count': '92092'},
     {'item': 'Ohio', 'count': '88000'},
     {'item': 'Minnesota', 'count': '87000'},
     {'item': 'Michigan', 'count': '83000'},
     {'item': 'Mississippi', 'count': '82000'},
     {'item': 'Puerto Rico', 'count': '78000'},
     {'item': 'Oklahoma', 'count': '77000'},
     {'item': 'Arkansas', 'count': '75000'},
     {'item': 'Wisconsin', 'count': '72000'}],
    'smallest': 'Alabama',
    'count': '3225222',
    'cardinality': '52'},
   'format': {}},
  {'id': 553949579,
   'name': 'county_name',
   'dataTypeName': 'text',
   'description': 'County',
   'fieldName': 'county_name',
   'position': 2,
   'renderTypeName': 'text',
   'tableColumnId': 138989113,
   'cachedContents': {'non_null': '3222560',
    'largest': 'Ziebach County',
    'null': '2662',
    'top': [{'item': 'Washington County', 'count': '30005'},
     {'item': 'Jefferson County', 'count': '25005'},
     {'item': 'Franklin County', 'count': '24005'},
     {'item': 'Jackson County', 'count': '23004'},
     {'item': 'Lincoln County', 'count': '23004'},
     {'item': 'Madison County', 'count': '19004'},
     {'item': 'Montgomery County', 'count': '18005'},
     {'item': 'Clay County', 'count': '18004'},
     {'item': 'Marion County', 'count': '17004'},
     {'item': 'Monroe County', 'count': '17004'},
     {'item': 'Union County', 'count': '17003'},
     {'item': 'Wayne County', 'count': '16003'},
     {'item': 'Greene County', 'count': '14004'},
     {'item': 'Warren County', 'count': '14003'},
     {'item': 'Grant County', 'count': '14002'},
     {'item': 'Carroll County', 'count': '13004'},
     {'item': 'Marshall County', 'count': '12004'},
     {'item': 'Johnson County', 'count': '12004'},
     {'item': 'Adams County', 'count': '12003'},
     {'item': 'Clark County', 'count': '12003'}],
    'smallest': 'Abbeville County',
    'count': '3225222',
    'cardinality': '2050'},
   'format': {}},
  {'id': 553949580,
   'name': 'fips_code',
   'dataTypeName': 'text',
   'description': 'County FIPS code, zero padded',
   'fieldName': 'fips_code',
   'position': 3,
   'renderTypeName': 'text',
   'tableColumnId': 138989111,
   'cachedContents': {'non_null': '3225222',
    'largest': '72153',
    'null': '0',
    'top': [{'item': '01003', 'count': '1001'},
     {'item': '01005', 'count': '1001'},
     {'item': '01007', 'count': '1001'},
     {'item': '01009', 'count': '1001'},
     {'item': '01011', 'count': '1001'},
     {'item': '01013', 'count': '1001'},
     {'item': '01015', 'count': '1001'},
     {'item': '01017', 'count': '1001'},
     {'item': '01019', 'count': '1001'},
     {'item': '01021', 'count': '1001'},
     {'item': '01023', 'count': '1001'},
     {'item': '01025', 'count': '1001'},
     {'item': '01027', 'count': '1001'},
     {'item': '01029', 'count': '1001'},
     {'item': '01031', 'count': '1001'},
     {'item': '01033', 'count': '1001'},
     {'item': '01035', 'count': '1001'},
     {'item': '01037', 'count': '1001'},
     {'item': '01039', 'count': '1001'},
     {'item': '01041', 'count': '1001'}],
    'smallest': '01001',
    'count': '3225222',
    'cardinality': '3222'},
   'format': {}},
  {'id': 553949581,
   'name': 'date',
   'dataTypeName': 'calendar_date',
   'description': 'Week ending date for the 7-day period for the case rate and the percent positivity',
   'fieldName': 'date',
   'position': 4,
   'renderTypeName': 'calendar_date',
   'tableColumnId': 138989110,
   'cachedContents': {'non_null': '3225222',
    'largest': '2022-10-18T00:00:00.000',
    'null': '0',
    'top': [{'item': '2020-01-22T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-23T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-24T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-25T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-26T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-27T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-28T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-29T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-30T00:00:00.000', 'count': '3222'},
     {'item': '2020-01-31T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-01T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-02T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-03T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-04T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-05T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-06T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-07T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-08T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-09T00:00:00.000', 'count': '3222'},
     {'item': '2020-02-10T00:00:00.000', 'count': '3222'}],
    'smallest': '2020-01-22T00:00:00.000',
    'count': '3225222',
    'cardinality': '1001'},
   'format': {'view': 'date'}},
  {'id': 553949582,
   'name': 'cases_per_100K_7_day_count_change',
   'dataTypeName': 'text',
   'description': 'Total number of new cases per 100,000 persons within the last 7 days',
   'fieldName': 'cases_per_100k_7_day_count',
   'position': 5,
   'renderTypeName': 'text',
   'tableColumnId': 138989108,
   'cachedContents': {'non_null': '3225222',
    'largest': 'suppressed',
    'null': '0',
    'top': [{'item': 'suppressed', 'count': '668301'},
     {'item': '0.000', 'count': '446387'},
     {'item': '149.031', 'count': '134'},
     {'item': '200.602', 'count': '98'},
     {'item': '210.084', 'count': '96'},
     {'item': '81.906', 'count': '93'},
     {'item': '103.627', 'count': '93'},
     {'item': '66.934', 'count': '92'},
     {'item': '105.820', 'count': '91'},
     {'item': '182.815', 'count': '91'},
     {'item': '232.558', 'count': '91'},
     {'item': '175.747', 'count': '88'},
     {'item': '167.785', 'count': '87'},
     {'item': '200.803', 'count': '86'},
     {'item': '106.045', 'count': '86'},
     {'item': '121.803', 'count': '85'},
     {'item': '139.860', 'count': '85'},
     {'item': '336.700', 'count': '85'},
     {'item': '73.206', 'count': '85'},
     {'item': '222.717', 'count': '85'}],
    'smallest': '0.000',
    'count': '3225222',
    'cardinality': '474747'},
   'format': {}},
  {'id': 553949583,
   'name': 'percent_test_results_reported_positive_last_7_days',
   'dataTypeName': 'number',
   'description': 'Percentage of positive diagnostic and screening nucleic acid amplification tests (NAAT) during the last 7 days',
   'fieldName': 'percent_test_results_reported',
   'position': 6,
   'renderTypeName': 'number',
   'tableColumnId': 138989109,
   'cachedContents': {'non_null': '2823884',
    'largest': '100.0',
    'null': '401338',
    'top': [{'item': '0.0', 'count': '195438'},
     {'item': '14.28571', 'count': '9938'},
     {'item': '16.66667', 'count': '9894'},
     {'item': '12.5', 'count': '9684'},
     {'item': '20.0', 'count': '9631'},
     {'item': '11.11111', 'count': '9238'},
     {'item': '10.0', 'count': '9149'},
     {'item': '9.09091', 'count': '8785'},
     {'item': '25.0', 'count': '8691'},
     {'item': '8.33333', 'count': '8348'},
     {'item': '7.69231', 'count': '8051'},
     {'item': '7.14286', 'count': '7624'},
     {'item': '6.66667', 'count': '7448'},
     {'item': '6.25', 'count': '7006'},
     {'item': '5.88235', 'count': '6663'},
     {'item': '33.33333', 'count': '6530'},
     {'item': '5.55556', 'count': '6370'},
     {'item': '5.26316', 'count': '6289'},
     {'item': '5.0', 'count': '5639'},
     {'item': '4.7619', 'count': '5329'}],
    'smallest': '0.0',
    'count': '3225222',
    'cardinality': '548104'},
   'format': {'precisionStyle': 'standard',
    'percentScale': '1',
    'precision': '2'}},
  {'id': 553949584,
   'name': 'community_transmission_level',
   'dataTypeName': 'text',
   'description': 'Community Transmission Level Indicator [low, moderate, substantial, high, blank]',
   'fieldName': 'community_transmission_level',
   'position': 7,
   'renderTypeName': 'text',
   'tableColumnId': 138989112,
   'cachedContents': {'non_null': '3202561',
    'largest': 'substantial',
    'null': '22661',
    'top': [{'item': 'high', 'count': '1846212'},
     {'item': 'low', 'count': '482482'},
     {'item': 'moderate', 'count': '481022'},
     {'item': 'substantial', 'count': '392845'}],
    'smallest': 'high',
    'count': '3225222',
    'cardinality': '4'},
   'format': {}}],
 'grants': [{'inherited': False, 'type': 'viewer', 'flags': ['public']}],
 'license': {'name': 'Public Domain U.S. Government',
  'termsLink': 'https://www.usa.gov/government-works'},
 'metadata': {'custom_fields': {'Data Quality': {'Geospatial Resolution': 'State, County',
    'Suggested Citation': 'Centers for Disease Control and Prevention, COVID-19 Response. United States COVID-19 County Level of Community Transmission Historical Changes - ARCHIVED (version date: October 20, 2022). '},
   'Common Core': {'Contact Email': 'cdcinfo@cdcinquiry.onmicrosoft.com',
    'References': 'https://data.cdc.gov/Public-Health-Surveillance/United-States-County-Level-of-Community-Transmissi/8396-v7yb',
    'Contact Name': 'CDC-INFO',
    'Update Frequency': 'No longer updated (dataset archived)',
    'Temporal Applicability': '2020-01-22/2022-10-18',
    'Program Code': '009:020',
    'Geographic Coverage': 'US',
    'Publisher': 'CDC',
    'Bureau Code': '009:20',
    'Public Access Level': 'public'}},
  'rowIdentifier': 553949585,
  'rowLabel': 'County Community Transmission Level by Date',
  'availableDisplayTypes': ['table', 'fatrow', 'page']},
 'owner': {'id': '5c5e-sht8',
  'displayName': 'NCIRD-CORVD',
  'screenName': 'NCIRD-CORVD',
  'type': 'interactive',
  'flags': ['acceptedEula', 'mayBeStoriesCoOwner']},
 'query': {},
 'rights': ['read'],
 'tableAuthor': {'id': '5c5e-sht8',
  'displayName': 'NCIRD-CORVD',
  'screenName': 'NCIRD-CORVD',
  'type': 'interactive',
  'flags': ['acceptedEula', 'mayBeStoriesCoOwner']},
 'tags': ['covid-19',
  'coronavirus',
  'laboratory',
  'cases',
  'county',
  'community transmission',
  'ncird-corvd'],
 'flags': ['default',
  'ownerMayBeContacted',
  'restorable',
  'restorePossibleForType']}

In [19]:
# This data only begins in 2021-08
#client.get_metadata("8396-v7yb")

In [20]:
query = """
SELECT 
    * 
WHERE 
    state_name != 'Puerto Rico'
LIMIT 
    600000000
"""

In [21]:
results = client.get(
    socrata_dataset_identifier, 
    query=query
)
client.close()

In [22]:
comtransmission = pd.DataFrame.from_records(results)
comtransmission

#no data for 2020 & 2021

,state_name,county_name,fips_code,date,cases_per_100k_7_day_count,community_transmission_level,percent_test_results_reported
0,Texas,Jackson County,48239,2020-01-27T00:00:00.000,0.000,NaN,NaN
1,Nebraska,Buffalo County,31019,2020-01-27T00:00:00.000,0.000,NaN,NaN
2,Illinois,Coles County,17029,2020-01-27T00:00:00.000,0.000,NaN,NaN
3,Iowa,Ida County,19093,2020-01-27T00:00:00.000,0.000,NaN,NaN
4,Tennessee,Knox County,47093,2020-02-05T00:00:00.000,0.000,low,NaN
...,...,...,...,...,...,...,...
3144555,Louisiana,Assumption Parish,22007,2022-10-18T00:00:00.000,suppressed,low,0.0
3144556,South Dakota,Hyde County,46069,2022-10-18T00:00:00.000,0.000,low,NaN
3144557,Texas,Loving County,48301,2022-10-18T00:00:00.000,suppressed,high,14.29
3144558,Virginia,Lynchburg City,51680,2022-10-18T00:00:00.000,26.770,substantial,8.01
3144559,Wyoming,Converse County,56009,2022-10-18T00:00:00.000,suppressed,moderate,5.19

In [23]:
states = comtransmission['state_name'].value_counts()
states

Texas                   254000
Georgia                 159000
Virginia                133000
Kentucky                120000
Missouri                115000
Kansas                  105000
Illinois                102000
North Carolina          100000
Iowa                     99099
Tennessee                95095
Nebraska                 93000
Indiana                  92092
Ohio                     88000
Minnesota                87000
Michigan                 83000
Mississippi              82000
Oklahoma                 77000
Arkansas                 75000
Wisconsin                72000
Alabama                  67067
Pennsylvania             67000
Florida                  67000
South Dakota             66001
Louisiana                64000
Colorado                 64000
New York                 62000
California               58058
Montana                  56000
West Virginia            55000
North Dakota             53000
South Carolina           46000
Idaho                    44000
Washington               39039
Oregon                   36000
New Mexico               33000
Alaska                   31031
Utah                     29000
Maryland                 24024
Wyoming                  23023
New Jersey               21000
Nevada                   17017
Maine                    16000
Arizona                  15000
Vermont                  14000
Massachusetts            14000
New Hampshire            10000
Connecticut               8008
Hawaii                    5005
Rhode Island              5000
Delaware                  3000
District of Columbia      1001
Name: state_name, dtype: int64

In [24]:
date = comtransmission['date'].value_counts()
date

2020-01-27T00:00:00.000    3144
2021-08-03T00:00:00.000    3144
2021-03-26T00:00:00.000    3144
2021-04-28T00:00:00.000    3144
2021-05-15T00:00:00.000    3144
                           ...
2022-04-09T00:00:00.000    3144
2022-04-18T00:00:00.000    3144
2022-04-21T00:00:00.000    3144
2022-10-18T00:00:00.000    3144
2022-10-17T00:00:00.000     560
Name: date, Length: 1001, dtype: int64

In [25]:
comtransmission.to_stata(fp+"/2_intermediate/"+"communitytransmisson_jan222020_oct182022"+".dta")